### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by SarvarKh** [SarvarKh/web-development-course#2]
Please leave your comment below if you have any

**Comment by akshay-narkar** [comment]
**Good Work on the project!** 

- Make use of gif instead of an mp4

**Comment by apricot12** [comment]
**Everything looks great, but a few things you should look at:**

- Change the main page video background to gif or still image.

- Make sure the nav-menu is visible in mobile mode.

- Move the HTML files to the root of the folder.

- Try to make the text for featured speakers larger.
